### ISSUE TITLE
Multi-Mod Conflicts with Newest Version

### ISSUE THREAD

**Issue by greensad** [AHilyard/MerchantMarkers#1]
### What's the issue you encountered?
Game stalls/freezes when booting(Mojang logo) when certain mods are used. Game must be closed manually.

### How can the issue be reproduced?
Launch the game with some combination of mods applied, wait for the game to begin loading. Strangely, it appears as though the stall or freeze only happens 3/4 of the time but after testing on three separate systems I have confirmed that the issue is unlikely to be hardware related. I have tried to narrow down what mods are causing the issue and I have found that disabling either MerchantMarkers or a combination of the following mods can allow the game to boot: 
-Effective
-Continuity
-Pipe
-Roughly Enough Items

However, launching the game with just those mods and MerchantMarkers(plus any required dependencies) does not result in a stall or freeze so there must be yet another conflict that I haven't been able to find. After messing about with this for a few hours I'm throwing in the towel, sorry I wasn't able to find the conflict, my hope is that you will have more luck given that you probably understand these things on a much deeper level.

### Logs.
https://paste.ee/p/3zEXo

### Multi-MC Instance Link.
https://drive.google.com/file/d/1sQ9mIBEc5m4mLdvKq8n92hDCA5QXQ9vQ/view?usp=sharing

**Comment by AHilyard** [comment]
I have not been able to reproduce this issue, are you still experiencing this?

**Comment by greensad** [comment]
> I have not been able to reproduce this issue, are you still experiencing this?

I just tried booting up my old 1.18.1 instance linked above for the first time in a few months and the issue immediately happened. Games been booting for 15 minutes now, considering I had left it on overnight previously I can say with some assurance that it will never boot. As I mentioned above I was unable to find all of the conflicting mods so I am unsure as to what is causing the stall/loading loop. Feel free to test the instance I had created for this issue linked above for yourself though, give it 5 launches and I'm confident the stall will occur on at least one of them.

**Comment by AHilyard** [comment]
I had previously tested your posted instance and couldn't get the stall to happen but just in case I tried again and after 8 tries, I finally experienced it. 
I've looked into it a bit and as far as I can tell the incompatibility is with DashLoader.  There seems to be a race condition causing the intermittent stalls.  This type of problem is pretty random as it comes down to when and what order things are loaded, when they are loaded in parallel.  Any changes to installed mods could affect if or how often it happens.  

Unfortunately, there's a good chance I will not be able to fix this from changes to Merchant Markers as I am not doing any threading in my mod, but I am admittedly doing some nonstandard stuff with dynamic resources to make the mod able to add dynamic icons to minimaps that normally don't support that.  I believe this is the main cause of the issue, but fixing it would require rewriting most of the mod.

Please try testing without DashLoader to confirm if that is the cause, it seems to have worked on my system at least.

**Comment by greensad** [comment]
> 

I'm really sorry to say, I gave it a go with Dashloader disabled but still stalled on first boot. I've been through my mods couple times looking for conflicts for this issue and I'm totally stumped. The fact that it doesn't stall every launch makes it far more difficult to test for as well : c

**Comment by AHilyard** [comment]
Ah dang, yeah that is really unfortunate.  I tried it 10 times and didn't get a stall so I assumed that was it but that just goes to show you how random these types of issues are. 
I don't have any plans currently to release any more updates for 1.18.1 now that 1.18.2 is out.  Perhaps some of these other mods have released updates since you initially set up this instance that will solve whatever the incompatibility is.  I will let you know when my 1.18.2 update for Fabric is available so we can test.

**Comment by greensad** [comment]
> Ah dang, yeah that is really unfortunate. I tried it 10 times and didn't get a stall so I assumed that was it but that just goes to show you how random these types of issues are. I don't have any plans currently to release any more updates for 1.18.1 now that 1.18.2 is out. Perhaps some of these other mods have released updates since you initially set up this instance that will solve whatever the incompatibility is. I will let you know when my 1.18.2 update for Fabric is available so we can test.

I think that's reasonable and tbh I was thinking the same thing. I've also moved on from 1.18.1 and will be happy to test when a 18.2 ver is available!

**Comment by greensad** [comment]
Well 1.19 isn't crashing for me, I'm gonna close the issue, thanks for you hard work!
