### ISSUE TITLE
[Request] Use Hold Keybind instead of Always Display

### ISSUE THREAD

**Issue by ardissaps** [AHilyard/MerchantMarkers#10]
Similiar to show player with Tab or user choosen keybind to show marker instead of always.

**Comment by AHilyard** [comment]
I like this idea, I'll consider it for the next update.

**Comment by AHilyard** [comment]
Just wanted to let you know that I've just released version 1.2.3 for 1.19/1.19.1 that includes this feature.  It is disabled by default, but if you turn it on in the config file you will be able to use a configurable keybind to show markers (defaults to left alt).

**Comment by ardissaps** [comment]
Thank you very much!
