### ISSUE TITLE
Merchant Markers quadruples my game's launch time.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [AHilyard/MerchantMarkers#12]
Without the mod, Minecraft takes roughly 25 seconds to launch. Applying this mod increased that to just over a minute and a half. The results were consistent. Tested three times.

[latest.log](https://github.com/AHilyard/MerchantMarkers/files/9523530/latest.log)

**Comment by AHilyard** [comment]
Interesting, I've just done some timing tests and received the following results with Forge 40.1.73:
```
no mods: 56 seconds
try 2: 52 seconds
only merchant markers: 44 seconds
try 2: 50 seconds
merchant markers + xaero minimap: 49 seconds
try 2: 48 seconds```
This is my elapsed time from pressing "Play" in the launcher to the game's main menu being fully loaded.  Can I get a mod list, and a log file from when you don't have Merchant Markers loading?

**Comment by JENOVAAbsolute** [comment]
Sure. I have more mods now than I did last last time, as I'm building a modpack. The image below is a screenshot of my modlist without Merchant Markers. Load time was the same as yesterday. Not even 30 seconds. There will be a log file without the mod as well.

![Untitled](https://user-images.githubusercontent.com/60951301/189201494-ae3ebaf4-bd4e-4837-820f-4a1c8

[latest.log](https://github.com/AHilyard/MerchantMarkers/files/9529834/latest.log)
7961a64.png)

**Comment by AHilyard** [comment]
I've tried installing what I can from this list and testing, but I'm still not getting any significant slowdown.  Is there a reason you've renamed all of these files?  It makes it very difficult to troubleshoot without the normal filenames, since I don't know exactly what you are using.
It would be very helpful if you could help troubleshoot by providing a minimal reproducible mod set.

**Comment by AHilyard** [comment]
Alternatively if you're using the CurseForge launcher, you can export the profile with config and mods and attach it so I can easily test the same setup.

**Comment by JENOVAAbsolute** [comment]
That is my OCD kicking in. I have a text file with links to every mod in the mod pack I'm putting together (so far). I'll put that here. I apologize for the inconvenience, as I know that is a habit that would make things harder for you.

[Modlist.txt](https://github.com/AHilyard/MerchantMarkers/files/9538548/Modlist.txt)

**Comment by JENOVAAbsolute** [comment]
I'm going to assume there's something on my end going on. I've temporarily removed client side mods and am adding them back once the mandatory mods are all in and tested. I'll worry about this again once I'm at that point. Though if you do find anything out, let me know. My friends I'm putting this pack together for to play with want your mod collection for the extra RPG feel. Can't say I disagree with them. Advancement plaques in particular is my favorite from your mods.
