### ISSUE TITLE
[1.21] Marker Blurred with JourneyMap

### ISSUE THREAD

**Issue by OriginCode** [AHilyard/MerchantMarkers#31]
![圖片](https://github.com/user-attachments/assets/824f91dc-607f-44b7-afa9-7adb1141a44b)

Log: https://mclo.gs/iuMHjA5
Mods: Fabric API, Iceberg, MerchantMarkers, JourneyMap

**Comment by AHilyard** [comment]
Thank you for the report, this has been resolved in the latest update.
