### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by aghostofstarman255** [AHilyard/MerchantMarkers#5]
Caused by going near villages or spawning villagers.
Newest versions of Forge and Iceberg and tested without any other mods.

[crash-2022-05-19_22.53.29-client.txt](https://github.com/AHilyard/MerchantMarkers/files/8735425/crash-2022-05-19_22.53.29-client.txt)

**Comment by AHilyard** [comment]
Thank you for reporting this, would you happen to still have the latest.log file that was generated for this run?  It contains a lot more contextual information than the crash log.

**Comment by AHilyard** [comment]
Actually I've just discovered the cause of the crash.  I erroneously set the minimum forge version required as 40.1.0, which is what you are using, but it should be 40.1.6.  I will release an update shortly that adds this requirement.

**Comment by AHilyard** [comment]
Iceberg version 1.0.42 is now available on CurseForge, which fixes this.  (1.0.41 is archived now)
Enjoy! 😄
