### ISSUE TITLE
Annoying Glowing Icon with Complementary Shadow

### ISSUE THREAD

**Issue by ardissaps** [AHilyard/MerchantMarkers#9]
![image](https://user-images.githubusercontent.com/82106625/176059925-121c6e8d-5ddf-4143-8033-03ba35527b0d.png)

1.18.2, with [MCA Villagers](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn)

**Comment by AHilyard** [comment]
Unfortunately this is a problem with Complementary Shaders.  I have spent a long time troubleshooting this particular issue and most shader packs do not have this problem.  You may be able to make the glow less intense by reducing the marker opacity in the config file.

**Comment by ardissaps** [comment]
Ok, I'll report to them, I have reduced the opacity, it was 50% in the screenshot.
